#!/usr/bin/env bash

set -e
set -o pipefail

echo "|> install gimme"
sudo curl -sL -o /usr/local/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
sudo chmod +x /usr/local/bin/gimme

echo "|> install Go"
gimme 1.8.3
source ~/.gimme/envs/go1.8.3.env

echo "|> install static asset tool"
go get github.com/mjibson/esc

echo "|> install Elm tooling"
npm install -g elm
npm install -g elm-test

echo "|> install sysconf"
cd /home/ubuntu
if [ ! -d sysconfcpus/bin ];
then
	git clone https://github.com/obmarg/libsysconfcpus.git
	cd libsysconfcpus
	./configure --prefix=/home/ubuntu/sysconfcpus
	make && make install
fi

echo "|> install Elm packages"
cd /home/ubuntu/snaas/cmd/console/tests
elm-package install -y

echo "|> prepare directories"
mkdir -p /home/ubuntu/.go_workspace/src/github.com/tapglue
rm -rf /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
cp -R /home/ubuntu/snaas /home/ubuntu/.go_workspace/src/github.com/tapglue/

echo "|> install Go packages"
cd /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
go get -d -v -t ./...
