#!/usr/bin/env bash

set -e
set -o pipefail

echo "|> install gimme"
sudo curl -sL -o /usr/local/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
sudo chmod +x /usr/local/bin/gimme

echo "|> install go"
gimme 1.7.5
source ~/.gimme/envs/go1.7.5.env

echo "|> prepare directories"
mkdir -p /home/ubuntu/.go_workspace/src/github.com/tapglue
rm -rf /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
cp -R /home/ubuntu/snaas /home/ubuntu/.go_workspace/src/github.com/tapglue/

echo "|> install packages"
cd /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
go get -d -v ./...