#!/usr/bin/env bash

set -e
set -o pipefail

echo "|> prepare env"
export CWD=$(pwd)
source ~/.gimme/envs/gotip.env

echo "|> execute tests"
cd /home/ubuntu/.go_workspace/src/github.com/tapglue/snaas
go test \
	-v \
	-race \
	./core/...

go test \
	-v \
	-race \
	./handler/...

go test \
	-v \
	-race \
	./platform/...

go test \
	-v \
	-race \
	-tags integration \
	./service/... \
	-postgres.url="postgres://ubuntu:unicode@127.0.0.1/circle_test?sslmode-disable"